# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:1.20
        # маршрутизируем порты
        ports:
            - "82:80"
        #    - "444:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    cron:
        build: ./images/cron
        volumes:
            - ./logs/nginx:/var/log/nginx
        links:
            - nginx
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        image: php:8.1-fpm
        #build: ./images/php
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www