name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./images
          
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./logs
